// Code generated by codegen from ddlmatrix/data/features.yaml. DO NOT EDIT.
//
// Verified: 2026-09-16

package ddlmatrix

// Feature identifies a DDL concurrency option.
type Feature string

const (
	// ONLINE = ON for index create/rebuild
	// Source: https://learn.microsoft.com/sql/sql-server/editions-and-components-of-sql-server-2025
	FeatureOnlineIndexOperations Feature = "online_index_operations"
	// WAIT_AT_LOW_PRIORITY
	// Source: https://learn.microsoft.com/sql/t-sql/statements/alter-index-transact-sql
	FeatureWaitAtLowPriority Feature = "wait_at_low_priority"
	// RESUMABLE = ON
	// Source: https://learn.microsoft.com/sql/t-sql/statements/alter-index-transact-sql
	FeatureResumable Feature = "resumable"
)

// StatementKind identifies the DDL statement an option is applied to. The
// supported version floor differs by statement kind, so this is not
// cosmetic: WAIT_AT_LOW_PRIORITY is 2014 for ALTER INDEX but 2022 for
// CREATE INDEX.
type StatementKind string

// StatementSupport is the version floor for one statement kind.
type StatementSupport struct {
	Kind       StatementKind
	MinVersion int // SQL Server release year; 0 when never supported
	Supported  bool
	Note       string
}

// FeatureInfo is everything known about one DDL concurrency option.
type FeatureInfo struct {
	ID   Feature
	Name string
	// Source is the Learn URL this entry was verified against.
	Source string
	// BoxRequiresEnterprise reports whether the box product gates this
	// feature on Enterprise-class editions.
	BoxRequiresEnterprise bool
	AzureSQLDatabase      bool
	ManagedInstance       bool
	// Requires lists features that must themselves be available first.
	// RESUMABLE requires ONLINE: evaluate the dependency before reporting,
	// or you produce advice with an unmentioned second blocker.
	Requires []Feature
	// Statements maps statement kind to its version floor.
	Statements []StatementSupport
	// ExcludedWhen lists conditions that make the feature unavailable for a
	// specific object regardless of platform.
	ExcludedWhen []string
	Notes        []string
}

var features = map[Feature]FeatureInfo{
	"online_index_operations": {
		ID:                    "online_index_operations",
		Name:                  "ONLINE = ON for index create/rebuild",
		Source:                "https://learn.microsoft.com/sql/sql-server/editions-and-components-of-sql-server-2025",
		BoxRequiresEnterprise: true,
		AzureSQLDatabase:      true,
		ManagedInstance:       true,
		Requires:              []Feature{},
		Statements: []StatementSupport{
			{Kind: "create_index", MinVersion: 2008, Supported: true, Note: ""},
			{Kind: "alter_index_rebuild", MinVersion: 2008, Supported: true, Note: ""},
			{Kind: "add_constraint_pk_unique", MinVersion: 2014, Supported: true, Note: ""},
			{Kind: "alter_column", MinVersion: 2016, Supported: true, Note: "narrow eligibility; type/size/collation changes that alter row layout cannot be online"},
		},
		ExcludedWhen: []string{
			"clustered index on a table containing image, ntext or text columns",
			"index on a local temp table (global temp tables are fine)",
			"XML index",
			"initial unique clustered index on a view",
			"disabled clustered index",
			"clustered columnstore on SQL Server 2017 and earlier",
			"nonclustered columnstore on SQL Server 2016 and earlier",
		},
		Notes: []string{
			"A nonunique nonclustered index CAN be built online when the table has LOB columns, provided none appear in the index definition as key or included columns.",
		},
	},
	"wait_at_low_priority": {
		ID:                    "wait_at_low_priority",
		Name:                  "WAIT_AT_LOW_PRIORITY",
		Source:                "https://learn.microsoft.com/sql/t-sql/statements/alter-index-transact-sql",
		BoxRequiresEnterprise: false,
		AzureSQLDatabase:      true,
		ManagedInstance:       true,
		Requires:              []Feature{},
		Statements: []StatementSupport{
			{Kind: "alter_index_rebuild", MinVersion: 2014, Supported: true, Note: ""},
			{Kind: "alter_table_rebuild", MinVersion: 2014, Supported: true, Note: ""},
			{Kind: "alter_table_switch", MinVersion: 2014, Supported: true, Note: ""},
			{Kind: "alter_database", MinVersion: 2014, Supported: true, Note: ""},
			{Kind: "create_index", MinVersion: 2022, Supported: true, Note: ""},
		},
		ExcludedWhen: []string{},
		Notes: []string{
			"Omitting the option equals WAIT_AT_LOW_PRIORITY (MAX_DURATION = 0, ABORT_AFTER_WAIT = NONE).",
			"ABORT_AFTER_WAIT = BLOCKERS requires ALTER ANY CONNECTION.",
			"ABORT_AFTER_WAIT = SELF cannot be used with MAX_DURATION = 0.",
			"Surfaces in wait stats as LCK_M_SCH_M_LOW_PRIORITY and LCK_M_S_LOW_PRIORITY.",
		},
	},
	"resumable": {
		ID:                    "resumable",
		Name:                  "RESUMABLE = ON",
		Source:                "https://learn.microsoft.com/sql/t-sql/statements/alter-index-transact-sql",
		BoxRequiresEnterprise: true,
		AzureSQLDatabase:      true,
		ManagedInstance:       true,
		Requires:              []Feature{"online_index_operations"},
		Statements: []StatementSupport{
			{Kind: "alter_index_rebuild", MinVersion: 2017, Supported: true, Note: ""},
			{Kind: "create_index", MinVersion: 2019, Supported: true, Note: ""},
			{Kind: "add_constraint_pk_unique", MinVersion: 2022, Supported: true, Note: ""},
			{Kind: "add_constraint_foreign_key", MinVersion: 0, Supported: false, Note: "never resumable in any version"},
		},
		ExcludedWhen: []string{
			"SORT_IN_TEMPDB = ON is requested",
			"the DDL runs inside an explicit transaction",
			"ALTER INDEX REBUILD ALL",
			"ALTER TABLE REBUILD",
			"columnstore index",
			"filtered index (check sys.indexes.has_filter)",
			"disabled index",
			"computed or timestamp column as a key column",
			"computed or LOB column as an included column",
			"table has CDC enabled (constraints only)",
			"memory-optimized or system table (constraints only)",
		},
		Notes: []string{
			"On Hyperscale, where SORT_IN_TEMPDB is normally always ON, RESUMABLE forces it OFF.",
			"Progress and state live in sys.index_resumable_operations; state_desc is only ever RUNNING or PAUSED — ABORT removes the row, there is no ABORTED state.",
			"While paused, a transaction needing a table-level X lock (INSERT ... WITH (TABLOCK)) fails with error 10637 rather than blocking.",
		},
	},
}

// Lookup returns the FeatureInfo for a feature id.
func Lookup(f Feature) (FeatureInfo, bool) {
	info, ok := features[f]
	return info, ok
}

// All returns every known feature id, for iteration in tests and reports.
func All() []Feature {
	out := make([]Feature, 0, len(features))
	for id := range features {
		out = append(out, id)
	}
	return out
}
