package main

const editionsTmpl = `// Code generated by codegen from platform/data/editions.yaml. DO NOT EDIT.
//
// Source: {{ .Source }}
// Verified: {{ .Verified }}

package platform

// EngineEdition is the value returned by SERVERPROPERTY('EngineEdition').
type EngineEdition int

// Family groups engine editions by the capability profile they imply.
type Family string

const (
	FamilyBox              Family = "box"
	FamilyManagedInstance  Family = "managed_instance"
	FamilyAzureSQLDatabase Family = "azure_sql_database"
	FamilySynapse          Family = "synapse"
	FamilyFabric           Family = "fabric"
	FamilyOther            Family = "other"
	FamilyUnknown          Family = "unknown"
)

const (
{{- range .EngineEditions }}
	// {{ .Name }}
	Edition{{ .Const }} EngineEdition = {{ .Value }}
{{- end }}
)

// EditionInfo describes one engine edition.
type EditionInfo struct {
	Value EngineEdition
	Name  string
	Family Family
	// Covers lists the product editions that report this EngineEdition.
	Covers []string
	// EnterpriseClass reports whether this edition carries the Enterprise
	// feature set (online index operations, resumable index operations).
	// Note that Standard Developer reports EditionStandard, so Developer
	// does NOT imply EnterpriseClass.
	EnterpriseClass bool
	// Obsolete marks editions no longer produced.
	Obsolete bool
	// Supported reports whether mssqlkit targets this edition.
	Supported bool
}

var editions = map[EngineEdition]EditionInfo{
{{- range .EngineEditions }}
	{{ .Value }}: {
		Value:           {{ .Value }},
		Name:            {{ quote .Name }},
		Family:          Family({{ quote .Family }}),
		Covers:          []string{ {{- range $i, $c := .Covers }}{{ if $i }}, {{ end }}{{ quote $c }}{{ end -}} },
		EnterpriseClass: {{ .EnterpriseClass }},
		Obsolete:        {{ .Obsolete }},
		Supported:       {{ if .Supported }}{{ .Supported }}{{ else }}{{ if eq .Family "box" }}true{{ else if eq .Family "managed_instance" }}true{{ else if eq .Family "azure_sql_database" }}true{{ else }}false{{ end }}{{ end }},
	},
{{- end }}
}

// Lookup returns the EditionInfo for an EngineEdition value. The second
// return is false for a value this table does not know, which must be
// reported as unknown rather than defaulted to anything.
func Lookup(e EngineEdition) (EditionInfo, bool) {
	info, ok := editions[e]
	return info, ok
}

// UpdatePolicy is the value returned by SERVERPROPERTY('ProductUpdateType')
// on Azure SQL Managed Instance. It gates features that are only available
// under the Always-up-to-date policy.
type UpdatePolicy string

const (
{{- range .UpdatePolicies.Values }}
	// {{ .Name }}
	UpdatePolicy{{ .Const }} UpdatePolicy = {{ quote .Value }}
{{- end }}
	UpdatePolicyUnknown UpdatePolicy = ""
)
`

const featuresTmpl = `// Code generated by codegen from ddlmatrix/data/features.yaml. DO NOT EDIT.
//
// Verified: {{ .Verified }}

package ddlmatrix

// Feature identifies a DDL concurrency option.
type Feature string

const (
{{- range .Features }}
	// {{ .Name }}
	// Source: {{ .Source }}
	Feature{{ goName .ID }} Feature = {{ quote .ID }}
{{- end }}
)

// StatementKind identifies the DDL statement an option is applied to. The
// supported version floor differs by statement kind, so this is not
// cosmetic: WAIT_AT_LOW_PRIORITY is 2014 for ALTER INDEX but 2022 for
// CREATE INDEX.
type StatementKind string

// StatementSupport is the version floor for one statement kind.
type StatementSupport struct {
	Kind       StatementKind
	MinVersion int  // SQL Server release year; 0 when never supported
	Supported  bool
	Note       string
}

// FeatureInfo is everything known about one DDL concurrency option.
type FeatureInfo struct {
	ID   Feature
	Name string
	// Source is the Learn URL this entry was verified against.
	Source string
	// BoxRequiresEnterprise reports whether the box product gates this
	// feature on Enterprise-class editions.
	BoxRequiresEnterprise bool
	AzureSQLDatabase      bool
	ManagedInstance       bool
	// Requires lists features that must themselves be available first.
	// RESUMABLE requires ONLINE: evaluate the dependency before reporting,
	// or you produce advice with an unmentioned second blocker.
	Requires []Feature
	// Statements maps statement kind to its version floor.
	Statements []StatementSupport
	// ExcludedWhen lists conditions that make the feature unavailable for a
	// specific object regardless of platform.
	ExcludedWhen []string
	Notes        []string
}

var features = map[Feature]FeatureInfo{
{{- range .Features }}
	{{ quote .ID }}: {
		ID:                    {{ quote .ID }},
		Name:                  {{ quote .Name }},
		Source:                {{ quote .Source }},
		BoxRequiresEnterprise: {{ .BoxRequiresEnterprise }},
		AzureSQLDatabase:      {{ .AzureSQLDatabase }},
		ManagedInstance:       {{ .ManagedInstance }},
		Requires:              []Feature{ {{- range $i, $r := .Requires }}{{ if $i }}, {{ end }}{{ quote $r }}{{ end -}} },
		Statements: []StatementSupport{
		{{- range .Statements }}
			{Kind: {{ quote .Kind }}, MinVersion: {{ .MinVersion }}, Supported: {{ if .Supported }}{{ .Supported }}{{ else }}{{ if eq .MinVersion 0 }}false{{ else }}true{{ end }}{{ end }}, Note: {{ quote .Note }}},
		{{- end }}
		},
		ExcludedWhen: []string{
		{{- range .ExcludedWhen }}
			{{ quote . }},
		{{- end }}
		},
		Notes: []string{
		{{- range .Notes }}
			{{ quote . }},
		{{- end }}
		},
	},
{{- end }}
}

// Lookup returns the FeatureInfo for a feature id.
func Lookup(f Feature) (FeatureInfo, bool) {
	info, ok := features[f]
	return info, ok
}

// All returns every known feature id, for iteration in tests and reports.
func All() []Feature {
	out := make([]Feature, 0, len(features))
	for id := range features {
		out = append(out, id)
	}
	return out
}
`

const buildsTmpl = `// Code generated by codegen from platform/data/builds.yaml. DO NOT EDIT.
//
// Source: {{ .Source }}
// Fetched: {{ .Fetched }}

package platform

// Build is one published SQL Server build.
type Build struct {
	Build       string // e.g. "16.0.4295.3"
	Product     string // e.g. "SQL Server 2022"
	Year        int    // e.g. 2022
	ServicePack string // "None" when not applicable
	Update      string // e.g. "CU27", "GDR", "CU26 + GDR"
	KB          string // e.g. "5104824"
	Released    string // ISO date, or "" when the page did not give one
}

// releases maps a major version prefix ("16.0") to its product name and year.
var releases = map[string]struct {
	Product string
	Year    int
}{
{{- range .Releases }}
	{{ quote .Major }}: { {{ quote .Product }}, {{ .Year }} },
{{- end }}
}

// builds is ordered by descending build within each major version, which is
// the order the source page publishes and the order ResolveBuild relies on.
var builds = []Build{
{{- range .Releases }}
{{- $product := .Product }}{{ $year := .Year }}
{{- range .Builds }}
	{Build: {{ quote .Build }}, Product: {{ quote $product }}, Year: {{ $year }}, ServicePack: {{ quote .ServicePack }}, Update: {{ quote .Update }}, KB: {{ quote .KB }}, Released: {{ quote .Released }}},
{{- end }}
{{- end }}
}
`
