// Code generated by codegen from platform/data/editions.yaml. DO NOT EDIT.
//
// Source: https://learn.microsoft.com/sql/t-sql/functions/serverproperty-transact-sql
// Verified: 2026-09-16

package platform

// EngineEdition is the value returned by SERVERPROPERTY('EngineEdition').
type EngineEdition int

// Family groups engine editions by the capability profile they imply.
type Family string

const (
	FamilyBox              Family = "box"
	FamilyManagedInstance  Family = "managed_instance"
	FamilyAzureSQLDatabase Family = "azure_sql_database"
	FamilySynapse          Family = "synapse"
	FamilyFabric           Family = "fabric"
	FamilyOther            Family = "other"
	FamilyUnknown          Family = "unknown"
)

const (
	// Personal or Desktop Engine
	EditionPersonal EngineEdition = 1
	// Standard
	EditionStandard EngineEdition = 2
	// Enterprise
	EditionEnterprise EngineEdition = 3
	// Express
	EditionExpress EngineEdition = 4
	// Azure SQL Database
	EditionAzureSQLDatabase EngineEdition = 5
	// Azure Synapse Analytics (dedicated SQL pool)
	EditionAzureSynapseDedicated EngineEdition = 6
	// Stretch Database
	EditionStretchDatabase EngineEdition = 7
	// Azure SQL Managed Instance
	EditionAzureSQLManagedInstance EngineEdition = 8
	// Azure SQL Edge
	EditionAzureSQLEdge EngineEdition = 9
	// Azure Arc Managed SQL Instance
	EditionAzureArcManagedInstance EngineEdition = 10
	// Azure Synapse serverless SQL pool, or Microsoft Fabric
	EditionAzureSynapseServerless EngineEdition = 11
	// SQL database in Microsoft Fabric
	EditionFabricSQLDatabase EngineEdition = 12
)

// EditionInfo describes one engine edition.
type EditionInfo struct {
	Value  EngineEdition
	Name   string
	Family Family
	// Covers lists the product editions that report this EngineEdition.
	Covers []string
	// EnterpriseClass reports whether this edition carries the Enterprise
	// feature set (online index operations, resumable index operations).
	// Note that Standard Developer reports EditionStandard, so Developer
	// does NOT imply EnterpriseClass.
	EnterpriseClass bool
	// Obsolete marks editions no longer produced.
	Obsolete bool
	// Supported reports whether mssqlkit targets this edition.
	Supported bool
}

var editions = map[EngineEdition]EditionInfo{
	1: {
		Value:           1,
		Name:            "Personal or Desktop Engine",
		Family:          Family("box"),
		Covers:          []string{},
		EnterpriseClass: false,
		Obsolete:        true,
		Supported:       true,
	},
	2: {
		Value:           2,
		Name:            "Standard",
		Family:          Family("box"),
		Covers:          []string{"Standard", "Standard Developer", "Web", "Business Intelligence"},
		EnterpriseClass: false,
		Obsolete:        false,
		Supported:       true,
	},
	3: {
		Value:           3,
		Name:            "Enterprise",
		Family:          Family("box"),
		Covers:          []string{"Enterprise", "Enterprise Developer", "Developer", "Evaluation"},
		EnterpriseClass: true,
		Obsolete:        false,
		Supported:       true,
	},
	4: {
		Value:           4,
		Name:            "Express",
		Family:          Family("box"),
		Covers:          []string{"Express", "Express with Tools", "Express with Advanced Services"},
		EnterpriseClass: false,
		Obsolete:        false,
		Supported:       true,
	},
	5: {
		Value:           5,
		Name:            "Azure SQL Database",
		Family:          Family("azure_sql_database"),
		Covers:          []string{},
		EnterpriseClass: true,
		Obsolete:        false,
		Supported:       true,
	},
	6: {
		Value:           6,
		Name:            "Azure Synapse Analytics (dedicated SQL pool)",
		Family:          Family("synapse"),
		Covers:          []string{},
		EnterpriseClass: false,
		Obsolete:        false,
		Supported:       false,
	},
	7: {
		Value:           7,
		Name:            "Stretch Database",
		Family:          Family("other"),
		Covers:          []string{},
		EnterpriseClass: false,
		Obsolete:        false,
		Supported:       false,
	},
	8: {
		Value:           8,
		Name:            "Azure SQL Managed Instance",
		Family:          Family("managed_instance"),
		Covers:          []string{},
		EnterpriseClass: true,
		Obsolete:        false,
		Supported:       true,
	},
	9: {
		Value:           9,
		Name:            "Azure SQL Edge",
		Family:          Family("other"),
		Covers:          []string{},
		EnterpriseClass: false,
		Obsolete:        false,
		Supported:       false,
	},
	10: {
		Value:           10,
		Name:            "Azure Arc Managed SQL Instance",
		Family:          Family("other"),
		Covers:          []string{},
		EnterpriseClass: false,
		Obsolete:        false,
		Supported:       false,
	},
	11: {
		Value:           11,
		Name:            "Azure Synapse serverless SQL pool, or Microsoft Fabric",
		Family:          Family("synapse"),
		Covers:          []string{},
		EnterpriseClass: false,
		Obsolete:        false,
		Supported:       false,
	},
	12: {
		Value:           12,
		Name:            "SQL database in Microsoft Fabric",
		Family:          Family("fabric"),
		Covers:          []string{},
		EnterpriseClass: false,
		Obsolete:        false,
		Supported:       false,
	},
}

// Lookup returns the EditionInfo for an EngineEdition value. The second
// return is false for a value this table does not know, which must be
// reported as unknown rather than defaulted to anything.
func Lookup(e EngineEdition) (EditionInfo, bool) {
	info, ok := editions[e]
	return info, ok
}

// UpdatePolicy is the value returned by SERVERPROPERTY('ProductUpdateType')
// on Azure SQL Managed Instance. It gates features that are only available
// under the Always-up-to-date policy.
type UpdatePolicy string

const (
	// Cumulative updates for the corresponding major SQL Server release
	UpdatePolicyCumulativeUpdate UpdatePolicy = "CU"
	// Always-up-to-date update policy
	UpdatePolicyAlwaysUpToDate UpdatePolicy = "Continuous"
	UpdatePolicyUnknown        UpdatePolicy = ""
)
