// Command fetchbuilds refreshes platform/data/builds.yaml from the published
// SQL Server build list on Microsoft Learn.
//
//	go run ./codegen/cmd/fetchbuilds
//
// This is a MAINTENANCE tool, deliberately separate from `go generate`:
//
//   - fetchbuilds needs the network and scrapes a page whose structure is not
//     a contract. It is run by a human (or a scheduled job) who then reviews
//     the diff.
//   - `go generate` is offline and deterministic: YAML in, Go out. CI can
//     verify it is up to date without touching the network.
//
// Because the source is not contractual, this tool fails loudly rather than
// degrading. An unexpected table header, a section with no rows, or a total
// build count below a sanity floor is an error — never a silently emptied
// file. A monitoring library that quietly forgets which SQL Server versions
// exist would give confidently wrong answers everywhere downstream.
package main

import (
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"time"

	"golang.org/x/net/html"
	"gopkg.in/yaml.v3"
)

const (
	sourceURL = "https://learn.microsoft.com/en-us/troubleshoot/sql/releases/download-and-install-latest-updates"

	// Sanity floor. The page has listed well over a thousand builds for
	// years; anything near zero means the structure changed and we parsed
	// nothing. Chosen low enough never to trip on a normal month.
	minBuilds = 200
	// Likewise for distinct product releases (2025, 2022, 2019, ...).
	minReleases = 5
)

// expectedHeader is the table header the parser understands. If Microsoft
// changes it, we stop rather than guess at column positions.
var expectedHeader = []string{
	"build number or version", "service pack", "update",
	"knowledge base number", "release date",
}

type buildRow struct {
	Build       string `yaml:"build"`
	ServicePack string `yaml:"service_pack"`
	Update      string `yaml:"update"`
	KB          string `yaml:"kb,omitempty"`
	Released    string `yaml:"released,omitempty"`
}

type release struct {
	Major   string     `yaml:"major"`
	Product string     `yaml:"product"`
	Year    int        `yaml:"year"`
	Builds  []buildRow `yaml:"builds"`
}

type doc struct {
	Source   string    `yaml:"source"`
	Fetched  string    `yaml:"fetched"`
	Note     string    `yaml:"note"`
	Releases []release `yaml:"releases"`
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "fetchbuilds:", err)
		os.Exit(1)
	}
}

func run() error {
	root, err := repoRoot()
	if err != nil {
		return err
	}

	body, err := fetch(sourceURL)
	if err != nil {
		return err
	}

	releases, err := parse(body)
	if err != nil {
		return err
	}

	total := 0
	for _, r := range releases {
		total += len(r.Builds)
	}
	if len(releases) < minReleases {
		return fmt.Errorf("parsed only %d releases (expected >= %d): the page structure likely changed",
			len(releases), minReleases)
	}
	if total < minBuilds {
		return fmt.Errorf("parsed only %d builds (expected >= %d): the page structure likely changed",
			total, minBuilds)
	}
	// Dates failing wholesale means the format changed. Fail rather than
	// emit a table whose release dates have silently vanished.
	if badDates*2 > total {
		return fmt.Errorf("%d of %d rows had an unparseable release date: the date format likely changed",
			badDates, total)
	}
	if badDates > 0 {
		fmt.Fprintf(os.Stderr,
			"fetchbuilds: warning: %d of %d rows had no parseable release date\n", badDates, total)
	}

	// Deterministic order: newest product first, builds already descending.
	sort.SliceStable(releases, func(i, j int) bool { return releases[i].Year > releases[j].Year })

	out := doc{
		Source:  sourceURL,
		Fetched: time.Now().UTC().Format("2006-01-02"),
		Note: "Generated by codegen/cmd/fetchbuilds. Do not hand-edit: rerun the tool. " +
			"The source page is documentation, not a contract - review the diff before committing.",
		Releases: releases,
	}

	var buf strings.Builder
	buf.WriteString("# SQL Server build list.\n")
	buf.WriteString("#\n")
	buf.WriteString("# Refresh with:  go run ./codegen/cmd/fetchbuilds\n")
	buf.WriteString("# Then regenerate Go with:  go generate ./...\n")
	buf.WriteString("#\n")
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(out); err != nil {
		return err
	}
	if err := enc.Close(); err != nil {
		return err
	}

	path := filepath.Join(root, "platform", "data", "builds.yaml")
	if err := os.WriteFile(path, []byte(buf.String()), 0o644); err != nil {
		return err
	}
	fmt.Printf("fetchbuilds: wrote %s (%d releases, %d builds)\n", path, len(releases), total)
	return nil
}

func repoRoot() (string, error) {
	wd, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for dir := wd; ; dir = filepath.Dir(dir) {
		if _, err := os.Stat(filepath.Join(dir, "go.work")); err == nil {
			return dir, nil
		}
		if parent := filepath.Dir(dir); parent == dir {
			return "", fmt.Errorf("go.work not found above %s", wd)
		}
	}
}

func fetch(url string) (*html.Node, error) {
	req, err := http.NewRequest(http.MethodGet, url, nil)
	if err != nil {
		return nil, err
	}
	req.Header.Set("User-Agent", "mssqlkit-fetchbuilds/1 (+https://github.com/rudi-bruchez/mssqlkit)")
	client := &http.Client{Timeout: 60 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("GET %s: %s", url, resp.Status)
	}
	// Bound the read: a runaway response should fail, not exhaust memory.
	limited := io.LimitReader(resp.Body, 32<<20)
	return html.Parse(limited)
}

var (
	// "SQL Server 2022", "SQL Server 2008 R2"
	productRe = regexp.MustCompile(`^SQL Server (\d{4})( R2)?$`)
	// A build is the first cell: 16.0.4295.3 / 10.50.6000.34 / 11.0.3000.00
	buildRe = regexp.MustCompile(`^\d{1,2}\.\d{1,2}\.\d+(\.\d+)?$`)
	kbRe    = regexp.MustCompile(`\b(\d{6,7})\b`)
)

// parse walks the document, pairing each `h3` product heading with the first
// table that follows it.
func parse(root *html.Node) ([]release, error) {
	var out []release
	var current *release

	var walk func(*html.Node) error
	walk = func(n *html.Node) error {
		if n.Type == html.ElementNode {
			switch n.Data {
			case "h2", "h3":
				title := strings.TrimSpace(text(n))
				if m := productRe.FindStringSubmatch(title); m != nil {
					year, _ := strconv.Atoi(m[1])
					out = append(out, release{Product: title, Year: year})
					current = &out[len(out)-1]
				} else {
					current = nil // a non-product heading ends the current section
				}
			case "table":
				if current == nil {
					return nil
				}
				rows, err := parseTable(n)
				if err != nil {
					return fmt.Errorf("%s: %w", current.Product, err)
				}
				if len(rows) == 0 {
					return nil
				}
				current.Builds = append(current.Builds, rows...)
				if current.Major == "" {
					current.Major = majorOf(rows[0].Build)
				}
				return nil // do not descend into the table again
			}
		}
		for c := n.FirstChild; c != nil; c = c.NextSibling {
			if err := walk(c); err != nil {
				return err
			}
		}
		return nil
	}
	if err := walk(root); err != nil {
		return nil, err
	}

	// Drop product sections that carried no build table (they exist for very
	// old versions), and reject any that parsed a table but no usable rows.
	kept := out[:0]
	for _, r := range out {
		if len(r.Builds) > 0 && r.Major != "" {
			kept = append(kept, r)
		}
	}
	return kept, nil
}

// badDates counts rows whose release date did not parse, across the whole
// run. A handful is normal on very old releases; a majority means the date
// format changed and the run must fail.
var badDates int

func parseTable(t *html.Node) ([]buildRow, error) {
	var rows [][]string
	var walk func(*html.Node)
	walk = func(n *html.Node) {
		if n.Type == html.ElementNode && n.Data == "tr" {
			var cells []string
			for c := n.FirstChild; c != nil; c = c.NextSibling {
				if c.Type == html.ElementNode && (c.Data == "td" || c.Data == "th") {
					cells = append(cells, strings.TrimSpace(text(c)))
				}
			}
			if len(cells) > 0 {
				rows = append(rows, cells)
			}
			return
		}
		for c := n.FirstChild; c != nil; c = c.NextSibling {
			walk(c)
		}
	}
	walk(t)

	if len(rows) == 0 {
		return nil, nil
	}

	// Only tables matching the expected header are build tables; anything
	// else on the page (the summary table, for instance) is skipped. A table
	// that looks like a build table but has a changed header is an error.
	head := rows[0]
	if len(head) != len(expectedHeader) {
		return nil, nil
	}
	for i, want := range expectedHeader {
		if !strings.EqualFold(strings.TrimSpace(head[i]), want) {
			// Header of the right width but wrong content: if the first data
			// row looks like a build, the structure changed under us.
			if len(rows) > 1 && buildRe.MatchString(rows[1][0]) {
				return nil, fmt.Errorf("unexpected table header %q (want %q) - the page structure changed",
					strings.Join(head, " | "), strings.Join(expectedHeader, " | "))
			}
			return nil, nil
		}
	}

	var out []buildRow
	for _, r := range rows[1:] {
		if len(r) != len(expectedHeader) {
			continue
		}
		b := strings.TrimSpace(r[0])
		if !buildRe.MatchString(b) {
			continue
		}
		released, dateOk := parseDate(r[4])
		if !dateOk {
			badDates++
		}
		out = append(out, buildRow{
			Build:       b,
			ServicePack: strings.TrimSpace(r[1]),
			Update:      strings.TrimSpace(r[2]),
			KB:          firstMatch(kbRe, r[3]),
			Released:    released,
		})
	}
	return out, nil
}

func majorOf(build string) string {
	parts := strings.SplitN(build, ".", 3)
	if len(parts) < 2 {
		return ""
	}
	return parts[0] + "." + parts[1]
}

func firstMatch(re *regexp.Regexp, s string) string {
	if m := re.FindStringSubmatch(s); m != nil {
		return m[1]
	}
	return ""
}

// parseDate normalises "September 15, 2026" to "2026-09-15".
//
// It returns ok=false rather than an empty string so the caller can count
// failures. Returning "" silently would contradict this tool's whole posture:
// a changed date format would quietly strip every release date from the table
// instead of failing, and nobody would notice until a consumer needed one.
func parseDate(s string) (string, bool) {
	s = strings.TrimSpace(s)
	if s == "" {
		return "", false
	}
	for _, layout := range []string{"January 2, 2006", "January 02, 2006", "Jan 2, 2006"} {
		if t, err := time.Parse(layout, s); err == nil {
			return t.Format("2006-01-02"), true
		}
	}
	return "", false
}

func text(n *html.Node) string {
	var sb strings.Builder
	var walk func(*html.Node)
	walk = func(n *html.Node) {
		if n.Type == html.TextNode {
			sb.WriteString(n.Data)
		}
		for c := n.FirstChild; c != nil; c = c.NextSibling {
			walk(c)
		}
	}
	walk(n)
	return strings.Join(strings.Fields(sb.String()), " ")
}
